package com.example.domain;

public class Articles {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articles.id
     *
     * @mbggenerated Fri May 22 17:15:12 JST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articles.name
     *
     * @mbggenerated Fri May 22 17:15:12 JST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articles.content
     *
     * @mbggenerated Fri May 22 17:15:12 JST 2020
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articles.id
     *
     * @return the value of articles.id
     *
     * @mbggenerated Fri May 22 17:15:12 JST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articles.id
     *
     * @param id the value for articles.id
     *
     * @mbggenerated Fri May 22 17:15:12 JST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articles.name
     *
     * @return the value of articles.name
     *
     * @mbggenerated Fri May 22 17:15:12 JST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articles.name
     *
     * @param name the value for articles.name
     *
     * @mbggenerated Fri May 22 17:15:12 JST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articles.content
     *
     * @return the value of articles.content
     *
     * @mbggenerated Fri May 22 17:15:12 JST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articles.content
     *
     * @param content the value for articles.content
     *
     * @mbggenerated Fri May 22 17:15:12 JST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}