package com.example.domain;

public class Comments {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.id
     *
     * @mbggenerated Fri May 22 17:15:12 JST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.name
     *
     * @mbggenerated Fri May 22 17:15:12 JST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.content
     *
     * @mbggenerated Fri May 22 17:15:12 JST 2020
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comments.article_id
     *
     * @mbggenerated Fri May 22 17:15:12 JST 2020
     */
    private Integer articleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.id
     *
     * @return the value of comments.id
     *
     * @mbggenerated Fri May 22 17:15:12 JST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.id
     *
     * @param id the value for comments.id
     *
     * @mbggenerated Fri May 22 17:15:12 JST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.name
     *
     * @return the value of comments.name
     *
     * @mbggenerated Fri May 22 17:15:12 JST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.name
     *
     * @param name the value for comments.name
     *
     * @mbggenerated Fri May 22 17:15:12 JST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.content
     *
     * @return the value of comments.content
     *
     * @mbggenerated Fri May 22 17:15:12 JST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.content
     *
     * @param content the value for comments.content
     *
     * @mbggenerated Fri May 22 17:15:12 JST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comments.article_id
     *
     * @return the value of comments.article_id
     *
     * @mbggenerated Fri May 22 17:15:12 JST 2020
     */
    public Integer getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comments.article_id
     *
     * @param articleId the value for comments.article_id
     *
     * @mbggenerated Fri May 22 17:15:12 JST 2020
     */
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }
}