package com.example.mapper;

import com.example.domain.Article;
import com.example.domain.ArticlesExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ArticleMapper {
	
	List<Article> selectArticle();
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articles
     *
     * @mbggenerated Fri May 22 17:15:12 JST 2020
     */
    int countByExample(ArticlesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articles
     *
     * @mbggenerated Fri May 22 17:15:12 JST 2020
     */
    int deleteByExample(ArticlesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articles
     *
     * @mbggenerated Fri May 22 17:15:12 JST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articles
     *
     * @mbggenerated Fri May 22 17:15:12 JST 2020
     */
    int insert(Article record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articles
     *
     * @mbggenerated Fri May 22 17:15:12 JST 2020
     */
    int insertSelective(Article record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articles
     *
     * @mbggenerated Fri May 22 17:15:12 JST 2020
     */
    List<Article> selectByExample(ArticlesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articles
     *
     * @mbggenerated Fri May 22 17:15:12 JST 2020
     */
    Article selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articles
     *
     * @mbggenerated Fri May 22 17:15:12 JST 2020
     */
    int updateByExampleSelective(@Param("record") Article record, @Param("example") ArticlesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articles
     *
     * @mbggenerated Fri May 22 17:15:12 JST 2020
     */
    int updateByExample(@Param("record") Article record, @Param("example") ArticlesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articles
     *
     * @mbggenerated Fri May 22 17:15:12 JST 2020
     */
    int updateByPrimaryKeySelective(Article record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articles
     *
     * @mbggenerated Fri May 22 17:15:12 JST 2020
     */
    int updateByPrimaryKey(Article record);
}